repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.138
    hooks:
    -   id: ruff
        args:
        - --fix

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
    -   id: isort
        name: isort (cython)
        types: [cython]
    -   id: isort
        name: isort (pyi)
        types: [pyi]

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black

-   repo: https://github.com/dosisod/refurb
    rev: 6977854c
    hooks:
    -   id: refurb

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
        additional_dependencies:
        - tomli

-   repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
        - id: sync_with_poetry
