"""
This file is automatically generated by torchmix and should not be changed.

This module contains wrapped versions of the objects in the PyTorch `nn`
module, intended to provide a more user-friendly interface and added
configuration management functionality.

These classes can be used as a drop-in replacement for the original PyTorch
`nn` module, allowing you to access the full configuration of the module
through the config attribute.
"""

import functools
from contextlib import suppress

from torch import nn

from torchmix.core._builds import BuildMode
from torchmix.core._component import Component

Module = nn.Module
Parameter = nn.Parameter
UninitializedBuffer = nn.UninitializedBuffer
UninitializedParameter = nn.UninitializedParameter

with suppress(AttributeError):
    factory_kwargs = nn.factory_kwargs

with suppress(AttributeError):
    functional = nn.functional

with suppress(AttributeError):
    init = nn.init

with suppress(AttributeError):
    modules = nn.modules

with suppress(AttributeError):
    parallel = nn.parallel

with suppress(AttributeError):
    parameter = nn.parameter

with suppress(AttributeError):
    utils = nn.utils


with suppress(AttributeError):

    class AdaptiveAvgPool1d(Component, nn.AdaptiveAvgPool1d):
        __init__ = functools.partial(nn.AdaptiveAvgPool1d.__init__)


with suppress(AttributeError):

    class AdaptiveAvgPool2d(Component, nn.AdaptiveAvgPool2d):
        __init__ = functools.partial(nn.AdaptiveAvgPool2d.__init__)


with suppress(AttributeError):

    class AdaptiveAvgPool3d(Component, nn.AdaptiveAvgPool3d):
        __init__ = functools.partial(nn.AdaptiveAvgPool3d.__init__)


with suppress(AttributeError):

    class AdaptiveLogSoftmaxWithLoss(Component, nn.AdaptiveLogSoftmaxWithLoss):
        __init__ = functools.partial(nn.AdaptiveLogSoftmaxWithLoss.__init__)


with suppress(AttributeError):

    class AdaptiveMaxPool1d(Component, nn.AdaptiveMaxPool1d):
        __init__ = functools.partial(nn.AdaptiveMaxPool1d.__init__)


with suppress(AttributeError):

    class AdaptiveMaxPool2d(Component, nn.AdaptiveMaxPool2d):
        __init__ = functools.partial(nn.AdaptiveMaxPool2d.__init__)


with suppress(AttributeError):

    class AdaptiveMaxPool3d(Component, nn.AdaptiveMaxPool3d):
        __init__ = functools.partial(nn.AdaptiveMaxPool3d.__init__)


with suppress(AttributeError):

    class AlphaDropout(Component, nn.AlphaDropout):
        __init__ = functools.partial(nn.AlphaDropout.__init__)


with suppress(AttributeError):

    class AvgPool1d(Component, nn.AvgPool1d):
        __init__ = functools.partial(nn.AvgPool1d.__init__)


with suppress(AttributeError):

    class AvgPool2d(Component, nn.AvgPool2d):
        __init__ = functools.partial(nn.AvgPool2d.__init__)


with suppress(AttributeError):

    class AvgPool3d(Component, nn.AvgPool3d):
        __init__ = functools.partial(nn.AvgPool3d.__init__)


with suppress(AttributeError):

    class BCELoss(Component, nn.BCELoss):
        __init__ = functools.partial(nn.BCELoss.__init__)


with suppress(AttributeError):

    class BCEWithLogitsLoss(Component, nn.BCEWithLogitsLoss):
        __init__ = functools.partial(nn.BCEWithLogitsLoss.__init__)


with suppress(AttributeError):

    class BatchNorm1d(Component, nn.BatchNorm1d):
        __init__ = functools.partial(nn.BatchNorm1d.__init__)


with suppress(AttributeError):

    class BatchNorm2d(Component, nn.BatchNorm2d):
        __init__ = functools.partial(nn.BatchNorm2d.__init__)


with suppress(AttributeError):

    class BatchNorm3d(Component, nn.BatchNorm3d):
        __init__ = functools.partial(nn.BatchNorm3d.__init__)


with suppress(AttributeError):

    class Bilinear(Component, nn.Bilinear):
        __init__ = functools.partial(nn.Bilinear.__init__)


with suppress(AttributeError):

    class CELU(Component, nn.CELU):
        __init__ = functools.partial(nn.CELU.__init__)


with suppress(AttributeError):

    class CTCLoss(Component, nn.CTCLoss):
        __init__ = functools.partial(nn.CTCLoss.__init__)


with suppress(AttributeError):

    class ChannelShuffle(Component, nn.ChannelShuffle):
        __init__ = functools.partial(nn.ChannelShuffle.__init__)


with suppress(AttributeError):

    class ConstantPad1d(Component, nn.ConstantPad1d):
        __init__ = functools.partial(nn.ConstantPad1d.__init__)


with suppress(AttributeError):

    class ConstantPad2d(Component, nn.ConstantPad2d):
        __init__ = functools.partial(nn.ConstantPad2d.__init__)


with suppress(AttributeError):

    class ConstantPad3d(Component, nn.ConstantPad3d):
        __init__ = functools.partial(nn.ConstantPad3d.__init__)


with suppress(AttributeError):

    class Container(Component, nn.Container):
        __init__ = functools.partial(nn.Container.__init__)


with suppress(AttributeError):

    class Conv1d(Component, nn.Conv1d):
        __init__ = functools.partial(nn.Conv1d.__init__)


with suppress(AttributeError):

    class Conv2d(Component, nn.Conv2d):
        __init__ = functools.partial(nn.Conv2d.__init__)


with suppress(AttributeError):

    class Conv3d(Component, nn.Conv3d):
        __init__ = functools.partial(nn.Conv3d.__init__)


with suppress(AttributeError):

    class ConvTranspose1d(Component, nn.ConvTranspose1d):
        __init__ = functools.partial(nn.ConvTranspose1d.__init__)


with suppress(AttributeError):

    class ConvTranspose2d(Component, nn.ConvTranspose2d):
        __init__ = functools.partial(nn.ConvTranspose2d.__init__)


with suppress(AttributeError):

    class ConvTranspose3d(Component, nn.ConvTranspose3d):
        __init__ = functools.partial(nn.ConvTranspose3d.__init__)


with suppress(AttributeError):

    class CosineEmbeddingLoss(Component, nn.CosineEmbeddingLoss):
        __init__ = functools.partial(nn.CosineEmbeddingLoss.__init__)


with suppress(AttributeError):

    class CosineSimilarity(Component, nn.CosineSimilarity):
        __init__ = functools.partial(nn.CosineSimilarity.__init__)


with suppress(AttributeError):

    class CrossEntropyLoss(Component, nn.CrossEntropyLoss):
        __init__ = functools.partial(nn.CrossEntropyLoss.__init__)


with suppress(AttributeError):

    class CrossMapLRN2d(Component, nn.CrossMapLRN2d):
        __init__ = functools.partial(nn.CrossMapLRN2d.__init__)


with suppress(AttributeError):

    class DataParallel(Component, nn.DataParallel):
        __init__ = functools.partial(nn.DataParallel.__init__)


with suppress(AttributeError):

    class Dropout(Component, nn.Dropout):
        __init__ = functools.partial(nn.Dropout.__init__)


with suppress(AttributeError):

    class Dropout1d(Component, nn.Dropout1d):
        __init__ = functools.partial(nn.Dropout1d.__init__)


with suppress(AttributeError):

    class Dropout2d(Component, nn.Dropout2d):
        __init__ = functools.partial(nn.Dropout2d.__init__)


with suppress(AttributeError):

    class Dropout3d(Component, nn.Dropout3d):
        __init__ = functools.partial(nn.Dropout3d.__init__)


with suppress(AttributeError):

    class ELU(Component, nn.ELU):
        __init__ = functools.partial(nn.ELU.__init__)


with suppress(AttributeError):

    class Embedding(Component, nn.Embedding):
        __init__ = functools.partial(nn.Embedding.__init__)


with suppress(AttributeError):

    class EmbeddingBag(Component, nn.EmbeddingBag):
        __init__ = functools.partial(nn.EmbeddingBag.__init__)


with suppress(AttributeError):

    class FeatureAlphaDropout(Component, nn.FeatureAlphaDropout):
        __init__ = functools.partial(nn.FeatureAlphaDropout.__init__)


with suppress(AttributeError):

    class Flatten(Component, nn.Flatten):
        __init__ = functools.partial(nn.Flatten.__init__)


with suppress(AttributeError):

    class Fold(Component, nn.Fold):
        __init__ = functools.partial(nn.Fold.__init__)


with suppress(AttributeError):

    class FractionalMaxPool2d(Component, nn.FractionalMaxPool2d):
        __init__ = functools.partial(nn.FractionalMaxPool2d.__init__)


with suppress(AttributeError):

    class FractionalMaxPool3d(Component, nn.FractionalMaxPool3d):
        __init__ = functools.partial(nn.FractionalMaxPool3d.__init__)


with suppress(AttributeError):

    class GELU(Component, nn.GELU):
        __init__ = functools.partial(nn.GELU.__init__)


with suppress(AttributeError):

    class GLU(Component, nn.GLU):
        __init__ = functools.partial(nn.GLU.__init__)


with suppress(AttributeError):

    class GRU(Component, nn.GRU):
        __init__ = functools.partial(nn.GRU.__init__)


with suppress(AttributeError):

    class GRUCell(Component, nn.GRUCell):
        __init__ = functools.partial(nn.GRUCell.__init__)


with suppress(AttributeError):

    class GaussianNLLLoss(Component, nn.GaussianNLLLoss):
        __init__ = functools.partial(nn.GaussianNLLLoss.__init__)


with suppress(AttributeError):

    class GroupNorm(Component, nn.GroupNorm):
        __init__ = functools.partial(nn.GroupNorm.__init__)


with suppress(AttributeError):

    class Hardshrink(Component, nn.Hardshrink):
        __init__ = functools.partial(nn.Hardshrink.__init__)


with suppress(AttributeError):

    class Hardsigmoid(Component, nn.Hardsigmoid):
        __init__ = functools.partial(nn.Hardsigmoid.__init__)


with suppress(AttributeError):

    class Hardswish(Component, nn.Hardswish):
        __init__ = functools.partial(nn.Hardswish.__init__)


with suppress(AttributeError):

    class Hardtanh(Component, nn.Hardtanh):
        __init__ = functools.partial(nn.Hardtanh.__init__)


with suppress(AttributeError):

    class HingeEmbeddingLoss(Component, nn.HingeEmbeddingLoss):
        __init__ = functools.partial(nn.HingeEmbeddingLoss.__init__)


with suppress(AttributeError):

    class HuberLoss(Component, nn.HuberLoss):
        __init__ = functools.partial(nn.HuberLoss.__init__)


with suppress(AttributeError):

    class Identity(Component, nn.Identity):
        __init__ = functools.partial(nn.Identity.__init__)


with suppress(AttributeError):

    class InstanceNorm1d(Component, nn.InstanceNorm1d):
        __init__ = functools.partial(nn.InstanceNorm1d.__init__)


with suppress(AttributeError):

    class InstanceNorm2d(Component, nn.InstanceNorm2d):
        __init__ = functools.partial(nn.InstanceNorm2d.__init__)


with suppress(AttributeError):

    class InstanceNorm3d(Component, nn.InstanceNorm3d):
        __init__ = functools.partial(nn.InstanceNorm3d.__init__)


with suppress(AttributeError):

    class KLDivLoss(Component, nn.KLDivLoss):
        __init__ = functools.partial(nn.KLDivLoss.__init__)


with suppress(AttributeError):

    class L1Loss(Component, nn.L1Loss):
        __init__ = functools.partial(nn.L1Loss.__init__)


with suppress(AttributeError):

    class LPPool1d(Component, nn.LPPool1d):
        __init__ = functools.partial(nn.LPPool1d.__init__)


with suppress(AttributeError):

    class LPPool2d(Component, nn.LPPool2d):
        __init__ = functools.partial(nn.LPPool2d.__init__)


with suppress(AttributeError):

    class LSTM(Component, nn.LSTM):
        __init__ = functools.partial(nn.LSTM.__init__)


with suppress(AttributeError):

    class LSTMCell(Component, nn.LSTMCell):
        __init__ = functools.partial(nn.LSTMCell.__init__)


with suppress(AttributeError):

    class LayerNorm(Component, nn.LayerNorm):
        __init__ = functools.partial(nn.LayerNorm.__init__)


with suppress(AttributeError):

    class LazyBatchNorm1d(Component, nn.LazyBatchNorm1d):
        __init__ = functools.partial(nn.LazyBatchNorm1d.__init__)


with suppress(AttributeError):

    class LazyBatchNorm2d(Component, nn.LazyBatchNorm2d):
        __init__ = functools.partial(nn.LazyBatchNorm2d.__init__)


with suppress(AttributeError):

    class LazyBatchNorm3d(Component, nn.LazyBatchNorm3d):
        __init__ = functools.partial(nn.LazyBatchNorm3d.__init__)


with suppress(AttributeError):

    class LazyInstanceNorm1d(Component, nn.LazyInstanceNorm1d):
        __init__ = functools.partial(nn.LazyInstanceNorm1d.__init__)


with suppress(AttributeError):

    class LazyInstanceNorm2d(Component, nn.LazyInstanceNorm2d):
        __init__ = functools.partial(nn.LazyInstanceNorm2d.__init__)


with suppress(AttributeError):

    class LazyInstanceNorm3d(Component, nn.LazyInstanceNorm3d):
        __init__ = functools.partial(nn.LazyInstanceNorm3d.__init__)


with suppress(AttributeError):

    class LazyLinear(Component, nn.LazyLinear):
        __init__ = functools.partial(nn.LazyLinear.__init__)


with suppress(AttributeError):

    class LeakyReLU(Component, nn.LeakyReLU):
        __init__ = functools.partial(nn.LeakyReLU.__init__)


with suppress(AttributeError):

    class Linear(Component, nn.Linear):
        __init__ = functools.partial(nn.Linear.__init__)


with suppress(AttributeError):

    class LocalResponseNorm(Component, nn.LocalResponseNorm):
        __init__ = functools.partial(nn.LocalResponseNorm.__init__)


with suppress(AttributeError):

    class LogSigmoid(Component, nn.LogSigmoid):
        __init__ = functools.partial(nn.LogSigmoid.__init__)


with suppress(AttributeError):

    class LogSoftmax(Component, nn.LogSoftmax):
        __init__ = functools.partial(nn.LogSoftmax.__init__)


with suppress(AttributeError):

    class MSELoss(Component, nn.MSELoss):
        __init__ = functools.partial(nn.MSELoss.__init__)


with suppress(AttributeError):

    class MarginRankingLoss(Component, nn.MarginRankingLoss):
        __init__ = functools.partial(nn.MarginRankingLoss.__init__)


with suppress(AttributeError):

    class MaxPool1d(Component, nn.MaxPool1d):
        __init__ = functools.partial(nn.MaxPool1d.__init__)


with suppress(AttributeError):

    class MaxPool2d(Component, nn.MaxPool2d):
        __init__ = functools.partial(nn.MaxPool2d.__init__)


with suppress(AttributeError):

    class MaxPool3d(Component, nn.MaxPool3d):
        __init__ = functools.partial(nn.MaxPool3d.__init__)


with suppress(AttributeError):

    class MaxUnpool1d(Component, nn.MaxUnpool1d):
        __init__ = functools.partial(nn.MaxUnpool1d.__init__)


with suppress(AttributeError):

    class MaxUnpool2d(Component, nn.MaxUnpool2d):
        __init__ = functools.partial(nn.MaxUnpool2d.__init__)


with suppress(AttributeError):

    class MaxUnpool3d(Component, nn.MaxUnpool3d):
        __init__ = functools.partial(nn.MaxUnpool3d.__init__)


with suppress(AttributeError):

    class Mish(Component, nn.Mish):
        __init__ = functools.partial(nn.Mish.__init__)


with suppress(AttributeError):

    class ModuleDict(Component, nn.ModuleDict):
        __init__ = functools.partial(nn.ModuleDict.__init__)


with suppress(AttributeError):

    class ModuleList(Component, nn.ModuleList):
        __init__ = functools.partial(nn.ModuleList.__init__)


with suppress(AttributeError):

    class MultiLabelMarginLoss(Component, nn.MultiLabelMarginLoss):
        __init__ = functools.partial(nn.MultiLabelMarginLoss.__init__)


with suppress(AttributeError):

    class MultiLabelSoftMarginLoss(Component, nn.MultiLabelSoftMarginLoss):
        __init__ = functools.partial(nn.MultiLabelSoftMarginLoss.__init__)


with suppress(AttributeError):

    class MultiMarginLoss(Component, nn.MultiMarginLoss):
        __init__ = functools.partial(nn.MultiMarginLoss.__init__)


with suppress(AttributeError):

    class MultiheadAttention(Component, nn.MultiheadAttention):
        __init__ = functools.partial(nn.MultiheadAttention.__init__)


with suppress(AttributeError):

    class NLLLoss(Component, nn.NLLLoss):
        __init__ = functools.partial(nn.NLLLoss.__init__)


with suppress(AttributeError):

    class NLLLoss2d(Component, nn.NLLLoss2d):
        __init__ = functools.partial(nn.NLLLoss2d.__init__)


with suppress(AttributeError):

    class PReLU(Component, nn.PReLU):
        __init__ = functools.partial(nn.PReLU.__init__)


with suppress(AttributeError):

    class PairwiseDistance(Component, nn.PairwiseDistance):
        __init__ = functools.partial(nn.PairwiseDistance.__init__)


with suppress(AttributeError):

    class ParameterDict(Component, nn.ParameterDict):
        __init__ = functools.partial(nn.ParameterDict.__init__)


with suppress(AttributeError):

    class ParameterList(Component, nn.ParameterList):
        __init__ = functools.partial(nn.ParameterList.__init__)


with suppress(AttributeError):

    class PixelShuffle(Component, nn.PixelShuffle):
        __init__ = functools.partial(nn.PixelShuffle.__init__)


with suppress(AttributeError):

    class PixelUnshuffle(Component, nn.PixelUnshuffle):
        __init__ = functools.partial(nn.PixelUnshuffle.__init__)


with suppress(AttributeError):

    class PoissonNLLLoss(Component, nn.PoissonNLLLoss):
        __init__ = functools.partial(nn.PoissonNLLLoss.__init__)


with suppress(AttributeError):

    class RNN(Component, nn.RNN):
        __init__ = functools.partial(nn.RNN.__init__)


with suppress(AttributeError):

    class RNNBase(Component, nn.RNNBase):
        __init__ = functools.partial(nn.RNNBase.__init__)


with suppress(AttributeError):

    class RNNCell(Component, nn.RNNCell):
        __init__ = functools.partial(nn.RNNCell.__init__)


with suppress(AttributeError):

    class RNNCellBase(Component, nn.RNNCellBase):
        __init__ = functools.partial(nn.RNNCellBase.__init__)


with suppress(AttributeError):

    class RReLU(Component, nn.RReLU):
        __init__ = functools.partial(nn.RReLU.__init__)


with suppress(AttributeError):

    class ReLU(Component, nn.ReLU):
        __init__ = functools.partial(nn.ReLU.__init__)


with suppress(AttributeError):

    class ReLU6(Component, nn.ReLU6):
        __init__ = functools.partial(nn.ReLU6.__init__)


with suppress(AttributeError):

    class ReflectionPad1d(Component, nn.ReflectionPad1d):
        __init__ = functools.partial(nn.ReflectionPad1d.__init__)


with suppress(AttributeError):

    class ReflectionPad2d(Component, nn.ReflectionPad2d):
        __init__ = functools.partial(nn.ReflectionPad2d.__init__)


with suppress(AttributeError):

    class ReflectionPad3d(Component, nn.ReflectionPad3d):
        __init__ = functools.partial(nn.ReflectionPad3d.__init__)


with suppress(AttributeError):

    class ReplicationPad1d(Component, nn.ReplicationPad1d):
        __init__ = functools.partial(nn.ReplicationPad1d.__init__)


with suppress(AttributeError):

    class ReplicationPad2d(Component, nn.ReplicationPad2d):
        __init__ = functools.partial(nn.ReplicationPad2d.__init__)


with suppress(AttributeError):

    class ReplicationPad3d(Component, nn.ReplicationPad3d):
        __init__ = functools.partial(nn.ReplicationPad3d.__init__)


with suppress(AttributeError):

    class SELU(Component, nn.SELU):
        __init__ = functools.partial(nn.SELU.__init__)


with suppress(AttributeError):

    class Sequential(Component, nn.Sequential):
        build_mode = BuildMode.WITH_ARGS
        __init__ = functools.partial(nn.Sequential.__init__)  # type: ignore


with suppress(AttributeError):

    class SiLU(Component, nn.SiLU):
        __init__ = functools.partial(nn.SiLU.__init__)


with suppress(AttributeError):

    class Sigmoid(Component, nn.Sigmoid):
        __init__ = functools.partial(nn.Sigmoid.__init__)


with suppress(AttributeError):

    class SmoothL1Loss(Component, nn.SmoothL1Loss):
        __init__ = functools.partial(nn.SmoothL1Loss.__init__)


with suppress(AttributeError):

    class SoftMarginLoss(Component, nn.SoftMarginLoss):
        __init__ = functools.partial(nn.SoftMarginLoss.__init__)


with suppress(AttributeError):

    class Softmax(Component, nn.Softmax):
        __init__ = functools.partial(nn.Softmax.__init__)


with suppress(AttributeError):

    class Softmax2d(Component, nn.Softmax2d):
        __init__ = functools.partial(nn.Softmax2d.__init__)


with suppress(AttributeError):

    class Softmin(Component, nn.Softmin):
        __init__ = functools.partial(nn.Softmin.__init__)


with suppress(AttributeError):

    class Softplus(Component, nn.Softplus):
        __init__ = functools.partial(nn.Softplus.__init__)


with suppress(AttributeError):

    class Softshrink(Component, nn.Softshrink):
        __init__ = functools.partial(nn.Softshrink.__init__)


with suppress(AttributeError):

    class Softsign(Component, nn.Softsign):
        __init__ = functools.partial(nn.Softsign.__init__)


with suppress(AttributeError):

    class SyncBatchNorm(Component, nn.SyncBatchNorm):
        __init__ = functools.partial(nn.SyncBatchNorm.__init__)


with suppress(AttributeError):

    class Tanh(Component, nn.Tanh):
        __init__ = functools.partial(nn.Tanh.__init__)


with suppress(AttributeError):

    class Tanhshrink(Component, nn.Tanhshrink):
        __init__ = functools.partial(nn.Tanhshrink.__init__)


with suppress(AttributeError):

    class Threshold(Component, nn.Threshold):
        __init__ = functools.partial(nn.Threshold.__init__)


with suppress(AttributeError):

    class Transformer(Component, nn.Transformer):
        __init__ = functools.partial(nn.Transformer.__init__)


with suppress(AttributeError):

    class TransformerDecoder(Component, nn.TransformerDecoder):
        __init__ = functools.partial(nn.TransformerDecoder.__init__)


with suppress(AttributeError):

    class TransformerDecoderLayer(Component, nn.TransformerDecoderLayer):
        __init__ = functools.partial(nn.TransformerDecoderLayer.__init__)


with suppress(AttributeError):

    class TransformerEncoder(Component, nn.TransformerEncoder):
        __init__ = functools.partial(nn.TransformerEncoder.__init__)


with suppress(AttributeError):

    class TransformerEncoderLayer(Component, nn.TransformerEncoderLayer):
        __init__ = functools.partial(nn.TransformerEncoderLayer.__init__)


with suppress(AttributeError):

    class TripletMarginLoss(Component, nn.TripletMarginLoss):
        __init__ = functools.partial(nn.TripletMarginLoss.__init__)


with suppress(AttributeError):

    class TripletMarginWithDistanceLoss(
        Component, nn.TripletMarginWithDistanceLoss
    ):
        __init__ = functools.partial(nn.TripletMarginWithDistanceLoss.__init__)


with suppress(AttributeError):

    class Unflatten(Component, nn.Unflatten):
        __init__ = functools.partial(nn.Unflatten.__init__)


with suppress(AttributeError):

    class Unfold(Component, nn.Unfold):
        __init__ = functools.partial(nn.Unfold.__init__)


with suppress(AttributeError):

    class Upsample(Component, nn.Upsample):
        __init__ = functools.partial(nn.Upsample.__init__)


with suppress(AttributeError):

    class UpsamplingBilinear2d(Component, nn.UpsamplingBilinear2d):
        __init__ = functools.partial(nn.UpsamplingBilinear2d.__init__)


with suppress(AttributeError):

    class UpsamplingNearest2d(Component, nn.UpsamplingNearest2d):
        __init__ = functools.partial(nn.UpsamplingNearest2d.__init__)


with suppress(AttributeError):

    class ZeroPad2d(Component, nn.ZeroPad2d):
        __init__ = functools.partial(nn.ZeroPad2d.__init__)
